mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutPage,
    AboutMeView,
    RegisterView,
    FooBarView,
    update_user_avatar,
    UsersListView,
    UserProfileView,
    UpdateUserAvatarView,
    HelloView,
)

app_name = "myauth"

urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path("hello/", HelloView.as_view(), name="hello"),
    path("users/", UsersListView.as_view(), name="users_list"),
    path("users/<int:pk>/", UserProfileView.as_view(), name="user_profile"),
    path("users/<int:pk>/update-avatar/", UpdateUserAvatarView.as_view(), name="update_user_avatar"),
    path("logout/", MyLogoutPage.as_view(), name="logout"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("register/", RegisterView.as_view(), name="register"),

    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),

    path("session/set/", set_session_view, name="session-set"),
    path("session/get/", get_session_view, name="session-get"),

    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps

urlpatterns = [
    path('api/', include('myapiapp.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name="schema"),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('blog/', include('blogapp.urls')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

urlpatterns += i18n_patterns(
    path('accounts/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
    path('admin/', admin.site.urls),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

mysite/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    ShopIndexView, GroupsListView,
    OrdersListView, ProductsListView, OrderDetailView,
    ProductDetailsView, ProductCreateView, ProductUpdateView,
    ProductDeleteView, OrderCreateView, OrderUpdateView, OrderDeleteView, ProductsDataExportView,
    OrdersExportView, ProductViewSet, OrderViewSet,
    LatestProductsFeed, UserOrdersListView, export_user_orders,
)

app_name = "shopapp"

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)


urlpatterns = [
    # path("", cache_page(60  * 3)(ShopIndexView.as_view()), name="index"),
    path("", ShopIndexView.as_view(), name="index"),
    path("api/", include(routers.urls)),
    path("groups/", GroupsListView.as_view(), name="groups_list"),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/export/", ProductsDataExportView.as_view(), name="products-export"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/archive/", ProductDeleteView.as_view(), name="product_delete"),
    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
    path("orders/export/", OrdersExportView.as_view(), name="orders-export"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_details"),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/delete/", OrderDeleteView.as_view(), name="order_delete"),
    path('products/latest/feed/', LatestProductsFeed(), name='products-feed'),
    path('users/<int:user_id>/orders/', UserOrdersListView.as_view(), name='user_orders'),
    path('users/<int:user_id>/orders/export/', export_user_orders, name='export_user_orders'),
]

mysite/shopapp/forms.py
from django.forms import ModelForm, forms, CheckboxSelectMultiple, formset_factory
from django.contrib.auth.models import Group
from .models import Order, ProductImage
from django import forms
from shopapp.models import Product

class OrderImportForm(forms.Form):
    file = forms.FileField()

class ProductForm(forms.ModelForm):
    images = forms.FileField(
        required=False
    )

    class Meta:
        model = Product
        fields = ('name', 'price', 'description', 'discount', 'preview')

class ProductImageForm(forms.ModelForm):
    image = forms.FileField(
        required=False
    )

    class Meta:
        model = ProductImage
        fields = ('image',)

ProductImageFormSet = forms.formset_factory(ProductImageForm, extra=5)


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ["name"]

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ("delivery_address", "promocode", "user", "products")
        widgets = {
            'products': CheckboxSelectMultiple(),
        }


class CSVImportForm(forms.Form):
    csv_file =  forms.FileField()

mysite/shopapp/views.py
"""
В этом модуле лежат различные наборы представлений.

Разные view интернет-магазина: по товарам, заказам и т.д.
"""

import logging
from timeit import default_timer
from csv import DictWriter

from django.contrib.auth.models import Group
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, reverse
from django.core.cache import cache
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.views.decorators.cache import cache_page
from rest_framework.viewsets import ModelViewSet
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.parsers import MultiPartParser
from rest_framework.decorators import action
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend

from .common import save_csv_products
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from drf_spectacular.utils import extend_schema, OpenApiResponse

from .forms import GroupForm, OrderForm
from .forms import ProductForm, ProductImageFormSet
from .models import Product, Order, ProductImage
from .serializers import ProductSerializer, OrderSerializer

from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from rest_framework import serializers

from django.contrib.syndication.views import Feed

log = logging.getLogger(__name__)

User = get_user_model()


class UserOrdersListView(LoginRequiredMixin, ListView):
    template_name = 'shopapp/orders_list.html'
    context_object_name = 'orders'

    def get_queryset(self):
        self.owner = get_object_or_404(User, id=self.kwargs['user_id'])
        return Order.objects.filter(user=self.owner).order_by('-pk')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['owner'] = self.owner
        return context


class LatestProductsFeed(Feed):
    title = "Shop products (latest)"
    description = "Updates on new products"
    link = reverse_lazy("shopapp:products")

    def items(self):
        return Product.objects.order_by("-created_at")[:5]

    def item_title(self, item: Product):
        return item.name

    def item_description(self, item: Product):
        return item.description[:200]

@extend_schema(description="Product views CRUD")
class ProductViewSet(ModelViewSet):
    """
    Набор представлений для действий над Product.

    Полный CRUD для сущностей товара.
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = ["name", "description"]
    filterset_fields = [
        "name",
        "description",
        "price",
        "discount",
        "archived"
    ]
    ordering_fields = [
        "name",
        "price",
        "discount",
    ]

    @method_decorator(cache_page(60 * 2))
    def list(self, *args, **kwargs):
        print("hello products list")
        return super().list(*args, **kwargs)

    @extend_schema(
        summary="Get one product by ID",
        description="Retrieves **product**, returns 404 if not found",
        responses={
            200: ProductSerializer,
            404: OpenApiResponse(description="Empty response, product by id not found"),
        }
    )
    def retrieve(self, *args, **kwargs):
        return super().retrieve(*args, **kwargs)

    @action(methods=["get"], detail=False)
    def download_csv(self, request: Request):

        response = HttpResponse(content_type="text/csv")
        filename = "products-export.csv"
        response["Content-Disposition"] = f"attachment; filename={filename}"
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            "name",
            "description",
            "price",
            "discount",
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()

        for product in queryset:
            writer.writerow({
                field: getattr(product, field)
                for field in fields
            })

        return response

    @action(
        detail=False,
        methods=["post"],
        parser_classes=[MultiPartParser],
    )
    def upload_csv(self, request: Request):
        products = save_csv_products(
            request.FILES["file"].file,
            encoding=request.encoding,
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)

class OrderViewSet(ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    filter_backends = [
        DjangoFilterBackend,
        OrderingFilter
    ]
    filterset_fields = [
        "user",
        "delivery_address",
        "promocode",
    ]
    ordering_fields = [
        "id",
        "user",
    ]

class OrdersExportView(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_staff

    def get(self, request):
        orders = Order.objects.select_related("user").prefetch_related("products")
        orders_data = [
            {
                "id": order.pk,
                "delivery_address": order.delivery_address,
                "promocode": order.promocode,
                "user_id": order.user.pk,
                "product_ids": [product.pk for product in order.products.all()],
            }
            for order in orders
        ]
        return JsonResponse({"orders": orders_data})

class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['image_formset'] = ProductImageFormSet()
        return context

    def form_valid(self, form):
        self.object = form.save()

        # Обработка множественных изображений
        image_formset = ProductImageFormSet(self.request.POST, self.request.FILES)
        if image_formset.is_valid():
            for image_form in image_formset:
                if image_form.cleaned_data:
                    ProductImage.objects.create(
                        product=self.object,
                        image=image_form.cleaned_data['image']
                    )

        return redirect(self.success_url)


class ProductUpdateView(PermissionRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = "shop.change_product"
    success_url = "/ru/shop/products/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['image_formset'] = ProductImageFormSet()
        return context

    def form_valid(self, form):
        self.object = form.save()

        # Обработка множественных изображений
        image_formset = ProductImageFormSet(self.request.FILES)
        if image_formset.is_valid():
            for image_form in image_formset:
                if image_form.cleaned_data:
                    ProductImage.objects.create(
                        product=self.object,
                        image=image_form.cleaned_data['image']
                    )

        return redirect(self.success_url)

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff


class ShopIndexView(View):

    # @method_decorator(cache_page(60 * 2))
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('Laptop', 1999),
            ('Desktop', 2999),
            ('Smartphone', 999)
        ]
        context = {
            "time_running": default_timer(),
            "products": products,
            "items": 5,
        }
        log.debug("Products for shop index: %s", products)
        log.info("Rendering shop index")
        print("shop index context", context)
        return render(request, 'shopapp/shop-index.html', context=context)

class GroupsListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            "form": GroupForm(),
            "groups": Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, 'shopapp/groups-list.html', context=context)

    def post(self, request: HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()

        return redirect(request.path)

class ProductDetailsView(DetailView):
    template_name = "shopapp/products-details.html"
    # model = Product
    queryset = Product.objects.prefetch_related("images")
    context_object_name = "product"

    def get_queryset(self):
        return Product.objects.filter(archived=False)

class ProductsListView(ListView):
    template_name = "shopapp/products-list.html"
    context_object_name = "products"
    queryset = Product.objects.filter(archived=False)

class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class OrdersListView(LoginRequiredMixin, ListView):
    queryset = (
        Order.objects
        .select_related("user")
        .prefetch_related("products")
        .all()
    )
    template_name = "shopapp/orders_list.html"
    context_object_name = "orders"

class OrderDetailView(PermissionRequiredMixin, DetailView):
    permission_required = "shopapp.view_order"
    queryset = (
        Order.objects
        .select_related("user")

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %}
        Base Title
      {% endblock %}
    </title>
</head>
<body>

{% block body %}
  Base body
{% endblock %}

<div>
  {% now 'H:i' %}
</div>
<div>
  {% now 'l' as current_weekday %}
  Today is {{ current_weekday }}
</div>
</body>
</html>

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Groups List
{% endblock %}

{% block body %}
  <h1>Groups:</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
  <div>
    {% if not groups %}
      <h3>No groups yet</h3>
    {% else %}
      <ul>

        {% for group in groups %}
          <li>
            <div>{{ group.name }}</div>
            <ul>

              {% for permissions in group.permissions.all %}
                <li>
                  {{ permissions.name }}
                  (<code>{{ permissions.codename }}</code>)
                </li>
              {% endfor %}

            </ul>
          </li>
        {% endfor %}

      </ul>
    {% endif %}
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Confirm delete order
{% endblock %}

{% block body %}
  <h1>Are you sure you want to delete order #{{ object.pk }}?</h1>
  <br>
  <div>
    <a href="{% url 'shopapp:order_details' pk=object.pk %}">Back to order details</a>
  </div>
  <br>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Delete</button>
    </form>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Order #{{ object.pk }} detail
{% endblock %}

{% block body %}
  <h1>Order #{{ object.pk }}</h1>
  <div>
    <p>Order by {% firstof object.user.first_name object.user.username %}</p>
    <p>Promocode: <code>{{ object.promocode }}</code></p>
    <p>Delivery address: {{ object.delivery_address }}</p>
    <div>
      Product in order:
      <ul>
        {% for product in object.products.all %}
          <li>{{ product.name }} for ${{ product.price }}</li>
        {% endfor %}

      </ul>
    </div>
  </div>

  <div>
    <a href="{% url 'shopapp:orders_list' %}">Back to orders list</a>
    <a href="{% url 'shopapp:order_update' pk=object.pk %}">Update order</a>
    <a href="{% url 'shopapp:order_delete' pk=object.pk %}">Delete order</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
  Orders List
{% endblock %}

{% block body %}
  <h1>Пользователь {{ owner.username }} выполнил следующие заказы:</h1>

  {% if object_list %}
    {% cache 300 user_orders owner.id %}
      <div>
        {% for order in object_list %}
          <div>
            <p><a href="{% url 'shopapp:order_details' pk=order.pk %}"
            >Details #{{ order.pk }}</a> </p>
            <p>Order by {% firstof order.user.first_name order.user.username %}</p>
            <p>Promocode: <code>{{ order.promocode }}</code></p>
            <p>Delivery address: {{ order.delivery_address }}</p>
            <div>
              Product in order:
              <ul>
                {% for product in order.products.all %}
                  <li>{{ product.name }} for ${{ product.price }}</li>
                {% endfor %}

              </ul>
            </div>
            <div>
              <a href="{% url 'shopapp:order_update' pk=order.pk %}">Update #{{ order.pk }}</a>
              <a href="{% url 'shopapp:order_delete' pk=order.pk %}">Delete #{{ order.pk }}</a>
            </div>

          </div>
        {% endfor %}
      </div>
    {% endcache %}
  {% else %}
    <h3>У пользователя {{ owner.username }} ещё нет заказов</h3>
  {% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Update order
{% endblock %}

{% block body %}
  <h1>Update order</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Update</button>
    </form>
  </div>
  <div>
    <a href="{% url 'shopapp:order_details' pk=object.pk %}">Back to order details</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/orders_changelist.html
{% extends "admin/change_list.html" %}
{% block object-tools %}
    {{ block.super }}
    <div class="actions">
        <a href="{% url 'admin:import_orders' %}" class="button">Импорт заказов</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Confirm archive {{ object.name }}
{% endblock %}

{% block body %}
  <h1>Are you sure you want to archive {{ object.name }}?</h1>
  <br>
  <div>
    <a href="{% url 'shopapp:product_details' pk=object.pk %}"
    >Back to product</a>
  </div>
  <br>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Archive</button>
    </form>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Create product
{% endblock %}

{% block body %}
  <h1>Create product</h1>
  <div>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      {{ image_formset.management_form }}
      {{ image_formset.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
  <div>
    <a href="{% url 'shopapp:products_list' %}"
    >Back to products list</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Update product
{% endblock %}

{% block body %}
  <h1>Update product</h1>
  <div>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Update</button>
    </form>
  </div>
  <div>
    <a href="{% url 'shopapp:product_details' pk=object.pk %}"
    >Back to product #{{ object.pk }}</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
  {% translate 'Product' %} #{{ product.pk }}
{% endblock %}

{% block body %}
  <h1>{% translate 'Product' %} <strong>{{ product.name }}</strong></h1>
  <div>
    <div>{% translate 'Description' %}: <em>{{ product.description }}</em></div>
    <div>{% translate 'Price' %}: {{ product.price }}</div>
    <div>{% translate 'Discount' %}: {{ product.discount }}</div>
    <div>{% translate 'Archived' %}: {{ product.archived }}</div>

    {% if product.preview %}
      <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
    {% endif %}

    <h3>{% translate 'Images' %}:</h3>
    <div>
      {% for img in product.images.all %}
        <div>
          <img src="{{ img.image.url }}" alt="{{ img.image.name }}">
          <div>{{ img.description }}</div>
        </div>
      {% empty %}
      <div>{% translate 'No images uploaded yet' %}</div>
      {% endfor %}

      {% if product.images.count == 1 %}
        {% translate 'There is 1 image available.' %}
      {% else %}
        {% blocktranslate count images_count=product.images.count %}
          There is only one image
          {% plural %}
          There are {{ images_count }} images available.
        {% endblocktranslate %}

      {% endif %}

    </div>
  </div>
  <div>
    <a href="{% url 'shopapp:product_update' pk=product.pk %}">{% translate 'Update product' %}</a>
  </div>
  <div>
    <a href="{% url 'shopapp:product_delete' pk=product.pk %}">{% translate 'Archive product' %}</a>
  </div>
  <div>
    <a href="{% url 'shopapp:products_list' %}">{% translate 'Back to products list' %}</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
  {% translate 'Products list' %}
{% endblock %}

{% block body %}
  <h1>{% translate 'Products' %}:</h1>
  {% if products %}
    <div>
      {% blocktranslate count products_count=products|length %}
        There is only one product
        {% plural %}
        There are {{ products_count }} products
      {% endblocktranslate %}
    </div>
    <div>
    {% for product in products %}
      <div>
        <p><a href="{% url 'shopapp:product_details' pk=product.pk %}"
        >{% translate 'Name' context 'product name' %}: {{ product.name }}</a></p>
        <p>{% translate 'Price' %}: {{ product.price }}</p>
        {% translate 'no discount' as no_discount %}
        <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</p>

        {% if product.preview %}
          <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
        {% endif %}
      </div>
    {% endfor %}

    </div>


    <div>
      <a href="{% url 'shopapp:product_create' %}"
      >{% translate 'Create a new product' %}</a>
    </div>
  {% else %}
    {% url 'shopapp:product_create' as create_product_url %}
    {% blocktranslate %}
      <h3>No products yet</h3>
      <a href="{{ create_product_url }}"
      >Create a new one</a>
    {% endblocktranslate %}
  {% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{% load admin_urls %}
    <li>
        <a href="{% url 'admin:import_products_csv' %}" class="addlink">
            Import CSV
        </a>
    </li>
    {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
    Shop Index
{% endblock %}

{% block body %}
    <h1>Hello Shop Index!</h1>

    <div>
        <ul>
            {% for name, price in products %}
                <li>{{ name }} ({{ name|length }}) for ${{ price }}</li>
                {% if name|length == 7 %}
                    <span>Lucky product!</span>
                {% endif %}
            {% empty %}
                No product here
            {% endfor %}
        </ul>
    </div>
    <div>
        Time running: {{ time_running }}
    </div>

    <div>
    <strong>
        You have {{ items }} cherr{{ items|pluralize:"y,ies" }}
    </strong>
    </div>

    {% cache 100 lorem %}
        <div>
            {% lorem 3 p random %}
        </div>
    {% endcache %}

{% endblock %}