mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutPage,
    AboutMeView,
    RegisterView,
    FooBarView,
    update_user_avatar,
    UsersListView,
    UserProfileView,
    UpdateUserAvatarView,
    HelloView,
)

app_name = "myauth"

urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path("hello/", HelloView.as_view(), name="hello"),
    path("users/", UsersListView.as_view(), name="users_list"),
    path("users/<int:pk>/", UserProfileView.as_view(), name="user_profile"),
    path("users/<int:pk>/update-avatar/", UpdateUserAvatarView.as_view(), name="update_user_avatar"),
    path("logout/", MyLogoutPage.as_view(), name="logout"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("register/", RegisterView.as_view(), name="register"),

    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),

    path("session/set/", set_session_view, name="session-set"),
    path("session/get/", get_session_view, name="session-get"),

    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps

urlpatterns = [
    path('api/', include('myapiapp.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name="schema"),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('blog/', include('blogapp.urls')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

urlpatterns += i18n_patterns(
    path('accounts/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
    path('admin/', admin.site.urls),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

mysite/myauth/models.py
from django.db import models
from django.contrib.auth.models import User

def user_avatar_directory_path(instance, filename):
    return "users/user_{pk}/avatar/{filename}".format(
        pk=instance.user.pk,
        filename=filename,
    )

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(upload_to=user_avatar_directory_path, null=True, blank=True)

mysite/myauth/forms.py
from django import forms
from .models import Profile

class UpdateAvatarForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar',)

mysite/myauth/views.py
from random import random

from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest, HttpResponse, JsonResponse, HttpResponseForbidden
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import CreateView, UpdateView, ListView, DetailView
from django.utils.translation import gettext_lazy as _, ngettext
from django.views.decorators.cache import cache_page

from django.contrib.auth.models import User
from .forms import UpdateAvatarForm
from .models import Profile

class HelloView(View):
    welcome_message = _("welcome hello world!")

    def get(self, request : HttpRequest) -> HttpResponse:
        items_str = request.GET.get("items") or 0
        items = int(items_str)
        product_line = ngettext(
            "one product",
            "{count} products",
            items,
        )
        product_line = product_line.format(count=items)

        return HttpResponse(
            f"<h1>{self.welcome_message}</h1>"
            f"\n<h2>{product_line}</h2>"
        )

class AboutMeView(UpdateView):
    model = Profile
    fields = ('avatar',)
    success_url = reverse_lazy('myauth:about-me')
    template_name = 'myauth/about-me.html'

    def get_object(self):
        try:
            return self.request.user.profile
        except Profile.DoesNotExist:
            return Profile.objects.create(user=self.request.user)

class UpdateUserAvatarView(UserPassesTestMixin, UpdateView):
    model = Profile
    fields = ('avatar',)
    template_name = 'myauth/update_user_avatar.html'

    # Автоматически получаем профиль через URL (pk)
    def get_success_url(self):
        return reverse('myauth:user_profile', kwargs={'pk': self.object.user.pk})

    # Проверка прав: is_staff или владелец профиля
    def test_func(self):
        profile = self.get_object()
        return self.request.user.is_staff or self.request.user == profile.user


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'myauth/register.html'
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response

@login_required
def about_me(request):
    try:
        user_profile = Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        user_profile = Profile.objects.create(user=request.user)

    if request.method == 'POST':
        form = UpdateAvatarForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('about_me')
    else:
        form = UpdateAvatarForm(instance=user_profile)

    return render(request, 'myauth/about-me.html', {'user_profile': user_profile, 'form': form})

def logout_view(request: HttpRequest):
    logout(request)
    return redirect(reverse("myauth:login"))

class MyLogoutView(LogoutView):
    next_page = reverse_lazy("myauth:login")

class MyLogoutPage(View):
    def get(self, request):
        logout(request)
        return redirect('myauth:login')

@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse('Cookie set')
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response

@cache_page(60 * 2)
def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("fizz", "default value")
    return HttpResponse(f"Cookie value: {value!r} + {random()}")

@permission_required("myauth.view_profile", raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["foobar"] = "spameggs"
    return HttpResponse("Session set!")

@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("foobar", "default")
    return HttpResponse(f"Session value: {value!r}")

class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({"foo": "bar", "spam": "eggs"})

def users_list(request):
    User = get_user_model()
    users = User.objects.all()
    return render(request, 'myauth/users_list.html', {'users': users})

def user_profile(request, pk):
    user = User.objects.get(pk=pk)
    try:
        user_profile = Profile.objects.get(user=user)
    except Profile.DoesNotExist:
        user_profile = None

    return render(request, 'myauth/user_profile.html', {'user': user, 'user_profile': user_profile})

@user_passes_test(lambda u: u.is_staff or u.pk == pk)
def update_user_avatar(request, pk):
    user = User.objects.get(pk=pk)
    try:
        user_profile = Profile.objects.get(user=user)
    except Profile.DoesNotExist:
        user_profile = None

    if request.method == 'POST':
        if user_profile:
            form = UpdateAvatarForm(request.POST, request.FILES, instance=user_profile)
            if form.is_valid():
                form.save()
                return redirect('myauth:user_profile', pk=pk)
        else:
            return HttpResponse("Профиль не найден")
    else:
        if user_profile:
            form = UpdateAvatarForm(instance=user_profile)
        else:
            form = None

    return render(request, 'myauth/update_user_avatar.html', {'form': form, 'user': user})

class UsersListView(ListView):
    model = User
    template_name = 'myauth/users_list.html'
    context_object_name = 'users'

class UserProfileView(DetailView):
    model = User
    template_name = 'myauth/user_profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            user_profile = Profile.objects.get(user=self.object)
        except Profile.DoesNotExist:
            user_profile = None
        context['user_profile'] = user_profile
        return context

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}
{% load cache %}

{% block title %}
  About me
{% endblock %}

{% block body %}
  <h1>User info</h1>
  <div>
    Products available: {% now "u" %}
  </div>
  {% if user.is_authenticated %}
    {% cache 300 userinfo user.username %}
      <h2>Detail</h2>
      <p>Username: {{ user.username }}</p>
      <p>First name: {{ user.first_name }}</p>
      <p>Last name: {{ user.last_name }}</p>
      <p>Email: {{ user.email }}</p>
      <p>Bio: {{ request.user.profile.bio }}</p>
    {% endcache %}
  {% else %}
    <h2>User is anonymous</h2>
  {% endif %}
  <div>
    {% if request.user.profile.avatar %}
      <img src="{{ request.user.profile.avatar.url }}" alt="Avatar">
    {% else %}
      <p>Аватарка не установлена</p>
    {% endif %}

    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Обновить аватарку</button>
    </form>
  </div>
{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}

        {% endblock %}</title>
</head>
<body>
    {% block body %}

    {% endblock %}
</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
  Login
{% endblock %}

{% block body %}

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Login</button>
  </form>

  <p><a href="{% url 'myauth:register' %}">Register</a></p>

  {% if request.user.is_authenticated %}
    <p><a href="{% url 'myauth:about-me' %}">About me</a></p>
  {% endif %}

{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
  Register
{% endblock %}

{% block body %}
  <h1>Register</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
  </form>
{% endblock %}

mysite/myauth/templates/myauth/update_user_avatar.html
{% extends 'myauth/base.html' %}

{% block body %}
    <h1>Обновить аватарку для {{ user.username }}</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Обновить аватарку</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/user_profile.html
{% extends 'myauth/base.html' %}

{% block body %}
    <h1>{{ user.username }}</h1>

    {% if user_profile and user_profile.avatar %}
        <img src="{{ user_profile.avatar.url }}" alt="Avatar">
    {% elif user_profile %}
        <p>Аватарка не установлена</p>
    {% else %}
        <p>Профиль не найден</p>
    {% endif %}

    {% if user_profile %}
        <p>Bio: {{ user_profile.bio }}</p>
        <p>Username: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
    {% endif %}

    {% if request.user.is_staff or request.user == user %}
        <a href="{% url 'myauth:update_user_avatar' user.profile.pk %}">Обновить аватарку</a>
    {% endif %}
{% endblock %}

mysite/myauth/templates/myauth/users_list.html
{% extends 'myauth/base.html' %}

{% block body %}
    <ul>
        {% for user in users %}
            <li>
                <a href="{% url 'myauth:user_profile' user.pk %}">{{ user.username }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}